static/style.css

fixes #
remove the horizontal scroll bar from website #18 
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
just hide every horizontal scrollbar in the body

[FIX] remove the horizontal scroll bar from website

---

index.html
static/style.css

fixes #
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

header color

---

about.html
contactus.html
index.html
static/style.css

I have deleted the About Us page content from Home Page and made a separate page for About Us Page. I have also formatted the content of About Us page to give it a better and well designed look.
NA

Made a separate About Us Page and customized it.

---

contactus.html
faq.html
index.html
mobile.html
product.html
static/style.css

Added a new faq page with some common questions keeping in mind the website theme and the responsiveness.
NA
Demo :

FAQ page changes

---

faq.html

Added the FAQ answers as suggested in PR #51 
NA

Additional FAQ Changes

---

faq.html
static/style.css

Added a custom scroll bar for all pages.
NA
Demo - 

Added Custom Scroll bar

---

about.html
contactus.html
dummy.html
faq.html
index.html
mobile.html
product.html
static/style.css

Fixes #17 
I have added a scroller from Bottom to Top using HTML , CSS , JS in every page of the Project.
NA

#17 Scroll to Top Button

---

.github/pull_request_template.md

Fixes #73
Removed a checklist point which was redundant.
DCP21

Removed Checklist point from pull_request_template.md

---

about.html
static/style.css

Reverts QAZIMAAZARSHAD/Apni-Dukaan#99

Revert "about us page"

---

contactus.html
static/form.js
static/style.css

@QAZIMAAZARSHAD 
Fixed the issues which you have said.
It resolves #30 
Its working video,
https://user-images.githubusercontent.com/75881393/125512337-28de19d1-7c59-4841-80c5-6523c8cdbaae.mp4

Fixed the required issues in Contact Us Functionality

---

index.html

Add Grow & shrink effect to cards of offers section in home page, use tachyons to add this effect.
NA
Hover over offer section in home page

Add Grow & shrink effect to cards of offers section in home page

---

Partner Stores.html
about.html
contactus.html
deals.html
dummy.html
faq.html
index.html
mobile.html
product.html
static/style.css
stationery.html

I modify the footer to be more attractive in index page.
-Hover over the link in footer, bold the link.
-Hover over the social media button, bold the link + add respective color to icon.
-Modify style of footer arrangement
-Checked and update the responsive footer

Modify footer to be more attractive

---

contactus.html
static/form.js

Added error checking on ContactUs page.
- Name, Email and Message input cannot be empty.
- Name input only accept alphabets and space (Digits and symbols are not allowed)
- Email input must be made up of _@_._ ( _ => refers to characters)
- If name or email input is invalid, submit button is disabled.
Added link to social media button and the email.

Added error checking in contactUs & Link social media

---

deals.html

I'll put a tag above the button consequently,  it will be more readable to users.
NA
visit deals of the day section

enhanced visibility of View Deal button inside deal of the day section

---

faq.html

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

Grammatical error in second last question of FAQ page. #142

---

Partner Stores.html
cart.html
contactus.html
deals.html
dummy.html
faq.html
index.html
login.html
mobile.html
product.html
static/style.css

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

Make same nav bar and footer for all the webpages

---

Partner Stores.html
cart.html
contactus.html
deals.html
dummy.html
faq.html
index.html
login.html
mobile.html
product.html
static/style.css

Reverts QAZIMAAZARSHAD/Apni-Dukaan#160

Revert "Make same nav bar and footer for all the webpages"

---

README.md

Reword READ.ME making sentences interesting
-->

Reword READ.ME

---

faq.html
static/style.css

I change the design of FAQ page. Example, I remove the accordian and replace by details,summary method which look more tidy. I added documentation on my modify part.
Screenshot of modify FAQ
N/A
- [/] I have mentioned related issue number in PR description.
- [/] I have added screenshots and related demo links of my changes..
- [/] The title of my pull request is a short description of the requested changes.
- [/] My code follows the code style of this project.
- [/] My change requires a change to the documentation.
- [/] I have updated the documentation accordingly.

Modify FAQ page (Fix #113)

---

Partner Stores.html
about.html
babyAndkids.html
books.html
cart.html
contactus.html
dummy.html
faq.html
home.html
login.html
mobile.html
offers.html
payment.html
product.html
stationery.html

Added "Our Partners" link in all the footers and linked it with the partners page

Added our partners link in footer

---

login.html
static/login.css

style login form

---

login.html
static/login.js
static/script.js

fix: signin

---

home.html

add login button on home navbar

---

cart.html
index.html

Fix: 41000 to 40100

---

cares.html

Fixed missing icons in contact us section from Apni Dukaan cares oage.

Fixed missing icons.

---

Partner Stores.html
about.html
babyAndkids.html
books.html
career.html
cares.html
cart.html
contactus.html
faq.html
home.html
mobile.html
offers.html
payment.html
paypolicy.html
privacy.html
product.html
shippolicy.html
stationery.html

It resolves issue #202 
Its screenshots,
Its link - https://k-jais.github.io/Apni-Dukaan/privacy.html

Added Privacy Policy page

---

static/style.css

Fix: streachy iamge

---

contactus.html

Fix : Home buttom on contact page

---

faq.html

add background to faq answer

---

home.html

add margin to box

---

about.html
faq.html
offers.html

here i made change in about.html and connect with it home page and i also made changes in offers.html and faq.html connect both of them with home page.

linked about page, offers page, faq page  with home pages.

---

faq.html
offers.html

Fixes #221
There was a runaway `>` that causes the size of the nav bar li item to increase in sieze hence the search bar and buttons also increases in size. 
Removing it solved the problem
NA

fix: search bar equal in size with the nav bar

---

home.html
index.html
static/load.css
static/load.js

Added preloader to index and home page with a white background and spinning spiral animation.
here is the link : https://admirable-manatee-393a76.netlify.app/
I don't think Adding website logo not good as the logo was not so good...
rest up to you...

Added preloader to index page

---

Partner Stores.html
about.html
babyAndkids.html
books.html
career.html
cares.html
cart.html
contactus.html
dummy.html
faq.html
furniture.html
home.html
mobile.html
offers.html
payment.html
paypolicy.html
privacy.html
product.html
shippolicy.html
stationery.html

- Added available `href` links to footer section.
- Replaced `href` links of same pages as `#` as a new link.
- I edited the `href` links of footer and add `./` as prefix in filepath.
[Click me](https://amjadnoor.github.io/Apni-Dukaan/) to check the changed code result.
Not at all

Available links added to footer

---

forgotPassword.html
login.html
static/login.js

1) Added a regular expression for email validation.
2) Added a regular expression for password validation. (added more constraints )
3) In login.js file added "return false" due to which data wont vanish after wrong entry.
4) added warning pop-up for  incorrect entries in email and password field.
5) added forgot password hyperlink .
Had to create  Blank forgotPassword .html page to add its hyperlink

Riya123-code added login page validations

---

offers.html

Updated image path to local image (discount.png) in images folder.

image path updated

---

README.md

Shopping! Who hate shopping? Everyone wants to get their hands on latest fashion trends and smartest new gadgets.
<p align="center"><img src="https://im.idiva.com/content/2015/Dec/shopping_10.gif" width = 70%></p>
Shopping with your best friends can be a fun experience! You get to spend some quality time, and bond over new trends. 
<p align="center"><img src="https://www.upbeatsoles.com/wp-content/uploads/2014/07/1-going-shopping.gif" width = 65%>></p>
But shopping with friends too can be a nightmare! Especially if your friends insist on taking a long walk in crowded bazaars, with stacks of cash, and heavy shopping bags.
<p align="center"><img src="https://media1.tenor.com/images/c5ddf9fb5699cd1f4d9d7268adb11f99/tenor.gif" width = 65%></p>
Now say goodbye to those tensions because [Apni …

Updated screenshots in Readme file

---

static/style.css

https://apni-dukaan-new.vercel.app/

added hover effect

---

index.html

#177 
The images in the landing page have been resized to fit the whole screen.
https://sanjanabharadwaj25.github.io/Apni-Dukaan/
NA

Fixed home/index image

---

mobile.html
static/mobile.css
static/style.css

No issue raised 
I have edited the mobile page. Aligned items and edited the CSS. I have made the page look much better and edited the CSS.
https://jahnvi15.github.io/Apni-Dukaan-hack/
NA
The navbar is not looking good. Although I am not able to edit the CSS
- [ x] I have mentioned related issue number in PR description.
- [x ] The title of my pull request is a short description of the requested changes.
- [ x] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.
- [x ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

Edited the Mobile page - Aligned items/Css edit

---

payment.html

> fixe a payment method page
fixes #25 
I am adding a payment method after clicking on the buy now button redirected to next page where a Razorpay payment method after that user made a payment and receives a payment receipt.

payment method
